### ISSUE TITLE
Incremental materialization with unique_key causes error

### ISSUE THREAD

**Issue by absorbb** [silentsokolov/dbt-clickhouse#12]
Hi!

It is great to have clickhouse dbt adapter.
But apparently it doesn't support unique_key for incremental materialization.

For model:
```sql
{{ config(
    materialized = 'incremental',
    unique_key = 'event_id',
    )}}

select * from integration_tests.incremental
{% if is_incremental() %}
where _timestamp >= (select max(_timestamp) from {{this}})
 {% endif %}
```
 
 dbt produces following code:
```sql
      delete
  from integration_tests.incremental_model
  where (event_id) in (
    select (event_id)
    from incremental_model__dbt_tmp
  )

  insert into integration_tests.incremental_model (_timestamp, event_id)
    select _timestamp, event_id
    from incremental_model__dbt_tmp;
```

that obviously won't run on clickhouse:
` DB::Exception: Syntax error: failed at position 176 ('delete') (line 3, col 7): delete`

Without unique_key we will have to handle repeated rows manually.

**Comment by absorbb** [comment]
@silentsokolov 
Still doesn't work.
Seems like semicolon is missing at the end of alter query.

``` 
alter table {{ target_relation }} {{ on_cluster_clause(label="on cluster") }} delete
  where ({{ unique_key }}) in (
    select ({{ unique_key }})
    from {{ tmp_relation }}
  )
  {%- endif %}

  insert into {{ target_relation }} ({{ dest_cols_csv }})```

**Comment by silentsokolov** [comment]
Please, send error log

**Comment by absorbb** [comment]
```
Database Error in model jitsu_events_plus_session_id (models/sessions/jitsu_events_plus_session_id.sql)
  Code: 62.
  DB::Exception: Syntax error: failed at position 374 ('insert') (line 10, col 3): insert into integration_tests.jitsu_events_plus_session_id (_timestamp, api_key, app, buildid, doc_encoding, doc_host, doc_path, doc_search, event_type, eventn_. Expected one of: DoubleColon, LIKE, GLOBAL NOT IN, end of query, DIV, IS, INTO OUTFILE, OR, QuestionMark, BETWEEN, NOT LIKE, MOD, AND, Comma, SETTINGS, IN, ILIKE, FORMAT, NOT ILIKE, NOT, token, NOT IN, GLOBAL IN. Stack trace:
  
  0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x8b5e67a in /usr/bin/clickhouse
  1. DB::parseQueryAndMovePosition(DB::IParser&, char const*&, char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, unsigned long, unsigned long) @ 0x12304868 in /usr/bin/clickhouse
  2. ? @ 0xfbc2cc8 in /usr/bin/clickhouse
  3. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, bool) @ 0xfbc28a3 in /usr/bin/clickhouse
  4. DB::TCPHandler::runImpl() @ 0x103e8d92 in /usr/bin/clickhouse
  5. DB::TCPHandler::run() @ 0x103fbc99 in /usr/bin/clickhouse
  6. Poco::Net::TCPServerConnection::start() @ 0x129f93af in /usr/bin/clickhouse
  7. Poco::Net::TCPServerDispatcher::run() @ 0x129fae3a in /usr/bin/clickhouse
  8. Poco::PooledThread::run() @ 0x12b34e39 in /usr/bin/clickhouse
  9. Poco::ThreadImpl::runnableEntry(void*) @ 0x12b30e2a in /usr/bin/clickhouse
  10. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
  11. clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
  compiled SQL at target/run/jitsu/models/sessions/jitsu_events_plus_session_id.sql

```

**Comment by silentsokolov** [comment]
Thanks again, fixed

**Comment by Caside** [comment]
Still don't work.

first i run model

`{{ config(materialized='table') }}

SELECT * FROM system.numbers LIMIT 5`

then i change model to incremental:

`{{
    config(
        materialized='incremental',
        unique_key='number'
    )
}}

SELECT * FROM system.numbers LIMIT 10`

Then i run incremental model and get this error:

` Code: 62.
  DB::Exception: Syntax error (Multi-statements are not allowed): failed at position 294 (end of query) (line 8, col 4): ;
  
    insert into internal_analytics.test_incremental (number)
      select number
      from test_incremental__dbt_tmp;
    . . Stack trace:
  
  0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x8d30bda in /usr/bin/clickhouse
  1. DB::parseQueryAndMovePosition(DB::IParser&, char const*&, char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, unsigned long, unsigned long) @ 0x12c874c8 in /usr/bin/clickhouse
  2. ? @ 0xfe15648 in /usr/bin/clickhouse
  3. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, bool) @ 0xfe151e3 in /usr/bin/clickhouse
  4. DB::TCPHandler::runImpl() @ 0x10691fe2 in /usr/bin/clickhouse
  5. DB::TCPHandler::run() @ 0x106a4f19 in /usr/bin/clickhouse
  6. Poco::Net::TCPServerConnection::start() @ 0x1337df2f in /usr/bin/clickhouse
  7. Poco::Net::TCPServerDispatcher::run() @ 0x1337f9ba in /usr/bin/clickhouse
  8. Poco::PooledThread::run() @ 0x134b2839 in /usr/bin/clickhouse
  9. Poco::ThreadImpl::runnableEntry(void*) @ 0x134aeaca in /usr/bin/clickhouse
  10. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
  11. __clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so
  compiled SQL at target/run/my_new_project/models/test_incremental.sql
`
and in target/run/ i get this:
`
      alter table internal_analytics.test_incremental 
   delete
  where (number) in (
    select (number)
    from test_incremental__dbt_tmp
  );

  insert into internal_analytics.test_incremental (number)
    select number
    from test_incremental__dbt_tmp;`

Our CH version: 21.6.5.37 (official build)
dbt core 0.20.1
