### ISSUE TITLE
"IndexError: no such group" for FixString column

### ISSUE THREAD

**Issue by burmecia** [silentsokolov/dbt-clickhouse#20]
When a column type is like `FixString(16)`, `dbt compile` will output `no such group` error. Might be a mistake in this line: https://github.com/silentsokolov/dbt-clickhouse/blob/b60f67ea24ce870a0108ee8194a6c29cb0d2cf70/dbt/adapters/clickhouse/column.py#L43

The regex it is using is https://github.com/silentsokolov/dbt-clickhouse/blob/b60f67ea24ce870a0108ee8194a6c29cb0d2cf70/dbt/adapters/clickhouse/column.py#L23

Should it be `char_size = int(match_sized.group(1))`?

**Comment by silentsokolov** [comment]
Thx!
