### ISSUE TITLE
Any reason not quote the column name?

### ISSUE THREAD

**Issue by burmecia** [silentsokolov/dbt-clickhouse#21]
I think the property name is `quoted` which is meant to return *quoted* column name, any reason why not doing that?

https://github.com/silentsokolov/dbt-clickhouse/blob/6f99be054e1a174a347bbb1e8743f44f94d4ae3a/dbt/adapters/clickhouse/column.py#L57

Should it be `return f'"{self.column}"'`?

**Comment by silentsokolov** [comment]
Switch to default
