### ISSUE TITLE
Bug float in csv seed file load as int

### ISSUE THREAD

**Issue by oleg-savko** [silentsokolov/dbt-clickhouse#24]
Seems like float in csv seed file load as int:

if I right understand problem is here:

https://github.com/silentsokolov/dbt-clickhouse/blob/master/dbt/adapters/clickhouse/connections.py
```
TODO: Convert to allow clickhouse type
format_bindings = []
for row in bindings.rows:
    format_row = []
    for v in row.values():
        if isinstance(v, Decimal):
            v = int(v)
        format_row.append(v)
    format_bindings.append(format_row)
```

**Comment by silentsokolov** [comment]
Show error message, please

**Comment by oleg-savko** [comment]
No error message here, but if in csv float number:

0.64,0.74,1.23

they load as int-s:
0,0,1
