### ISSUE TITLE
UI for DBT using dbt-clickhouse

### ISSUE THREAD

**Issue by sandeep-devarapalli** [silentsokolov/dbt-clickhouse#30]
Hi, I am very interested to work on enabling a UI for DBT using dbt-clickhouse at the backend. If you can guide me, it would be of great help, and anyone interested is welcome to be a part of this, thanks.

**Comment by silentsokolov** [comment]
Hello, DBT already has a UI. I think you can create a topic with same question in [official repo](https://github.com/dbt-labs/dbt-core/discussions). Thanks for your interest in the project!

**Comment by sandeep-devarapalli** [comment]
Thank you for the suggestion, I will create a topic over there.

**Comment by vargacypher** [comment]
@sandeep-devarapalli Maybe you can create an REST API or RPC to make calls on your DBT service.
We made this with FastAPI + Python RQ, were we can interact direclty with swagger. But you can implement a front-end app toghether.
