### ISSUE TITLE
Support for TTL config

### ISSUE THREAD

**Issue by kjdeluna** [silentsokolov/dbt-clickhouse#33]
Can we add support for TTL in tables?

**Comment by silentsokolov** [comment]
Sure! Any pull requests are cool

**Comment by kjdeluna** [comment]
I would like to! Do you have any guide how to set it up in my local so I could test it out?

**Comment by silentsokolov** [comment]
You can start with [official guide](https://docs.getdbt.com/docs/contributing/building-a-new-adapter#testing-your-new-adapter), but you can work as you please (virtualanv, pyenv, etc), for example I add dbt-clickhouse (repo code) to my `PYTHONPATH` and run the tests or the models on my local clickhouse (docker)
