### ISSUE TITLE
Support for ON CLUSTER clause

### ISSUE THREAD

**Issue by d1bevz** [silentsokolov/dbt-clickhouse#4]
Could not find any reference how to set [ON CLUSTER clause](https://clickhouse.tech/docs/en/sql-reference/statements/create/settings-profile/)

**Comment by d1bevz** [comment]
I need to create materialized table based on dbt-model on specific cluster, is it possible to set cluster in `{{config()}}`?

Will adapter create query like in docs for Clickhouse
```
CREATE TABLE IF NOT EXISTS table_name **ON CLUSTER cluster_name**
(
    bla-bla
) ENGINE = engine

```

**Comment by silentsokolov** [comment]
`ON CLUSTER` is not support. 
I will try to add this.

**Comment by silentsokolov** [comment]
I added `ON CLUSTER` in PR #6. But I don't have a cluster clickhouse, so ran only on synthetic tests on simple cases.

**Comment by d1bevz** [comment]
I think two parameters should be added with on_cluster clause, my server falls with the following error:
```
Orig exception: Code: 42, e.displayText() = DB::Exception: There was an error on [X]: Code: 42, e.displayText() = DB::Exception: With extended storage definition syntax storage ReplicatedMergeTree requires 2 parameters: 
  path in ZooKeeper,
  replica name

```

**Comment by silentsokolov** [comment]
Now on `master` you can set the engine with brackets (`ReplicatedMergeTree` -> `ReplicatedMergeTree(your options)`

**Comment by silentsokolov** [comment]
`ON CLUSTER` on master.
Reopen if needed.

**Comment by d1bevz** [comment]
> Now on `master` you can set the engine with brackets (`ReplicatedMergeTree` -> `ReplicatedMergeTree(your options)`

yeah, but ZooKeeper path is dependent on relation that will be created by dbt. this means path could be different depending on dbt-model execution

I'll test and if needed will commit couple lines in macros
