### ISSUE TITLE
dbt init not working

### ISSUE THREAD

**Issue by d1bevz** [silentsokolov/dbt-clickhouse#5]
I run `dbt init project_name --adapter=clickhouse` and got following error:

> Running with dbt=0.19.0
> Creating dbt configuration folder at /Users/username/.dbt
> With sample profiles.yml for clickhouse
> Encountered an error:
> Runtime Error
>   No sample profile for clickhouse

But I already have profiles.yml with configured profile for my connection

**Comment by silentsokolov** [comment]
Thank you, added `sample_profiles.yml`. Now will be ok
